apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd  
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 75.6.0 # Replace with desired version
      helm:
        valueFiles:
          - $values/monitoring/grafana-values.yaml
    - repoURL: https://github.com/LikithaRavi1/kubeace.com 
      targetRevision: main                                
      ref: values                                        
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
